name: Move closed issues

on:
  issues:
    types: [closed]

jobs:
  automate-project-columns:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Badi
          column: Closed
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
